### ISSUE TITLE
Font size changing unexpectedly in results

### ISSUE THREAD

**Issue by sohanvanani** [apasccon/SearchTextField#34]
While selecting custom fonts search results displaying randomly unexpected size. Please refer screenshot attached here.
![screen shot 2017-04-16 at 2 27 20 am](https://cloud.githubusercontent.com/assets/11327387/25066720/4a5a0bf8-224c-11e7-9a11-46020956c642.png)

**Comment by bakeddean** [comment]
I think if you are going to set a custom font, you need to set the highlightAttributes as well:
```
textField.highlightAttributes = [NSFontAttributeName: UIFont.boldSystemFont(ofSize: 15)]
```
or however you want to style the highlighted search text.

**Comment by GHarte** [comment]
Hi, I ran into this problem and thought it was a bug too but it isn't. It is done to show where the text you have entered was found in your Strings.

If you look through the source code you will see on line 68: 
`/// Set your custom set of attributes in order to highlight the string found in each item
    open var highlightAttributes: [String: AnyObject] = [NSFontAttributeName:UIFont.boldSystemFont(ofSize: 10)]`

So, as a quick example to stop this from happening you can set the theme font and highlightAttributes to be the same: 

`myTextField.theme.font = UIFont.systemFont(ofSize: 14)`
`myTextField.highlightAttributes = [NSFontAttributeName:UIFont.systemFont(ofSize: 14)]`

Hope this helps.

**Comment by GHarte** [comment]
@bakeddean beat me to it by a couple of seconds! 👍
